### ISSUE TITLE
ENZIP 11: Growing the Enzyme Technical Council

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/MIP#11]
ENZIP: 11
Title: Growing the Enzyme Council and working towards Governance 2.0
Author: Mona El Isa, Avantgarde
Status: Draft - discussed in council meetings, iterated and officially voted on [snapshot](https://snapshot.org/#/enzymefinance.eth/proposal/0xf41ea9ff39ca4a96022b711db5941a36c29cbbbdce9b5d1988d6e19279c30079)
Type: ENZIP
Created: Feb 22nd, 2021

**Background**
In February 2019, Enzyme Council came into play as the first DeFi protocol to decentralise its governance. We structured the Council as a technically skilled and user representative group of people and granted the decision making authority of the following actions to the Council:

- Protocol upgrades
- Protocol parameterisation
- Grants & Ecosystem funding

We’ve managed to maintain a stable governance process throughout. However, with the recent growth of the protocol and the roadmap ahead, the workload is only increasing and having one council to do all tasks isn’t the most optimal way forward.

This proposal served to explore the possible future direction of the council as well as a call to action to encourage new applicants to get in touch!

**Governance 2.0: Expanding into squads and adding new members**

The council is currently made up of technical and experienced users but they all have different skill sets. The idea of breaking up the protocol into squads should enable higher efficiency and throughput for what the council (and protocol) can deliver.

As the protocol grows in complexity and we start to imagine multiple deployments on different chains, it is likely that the workload of the technical council is going to grow exponentially and thus the governance required with it. As a result of this, we proposed splitting the council into squads which focus on different aspects of the protocol.

**Squad 1:** Protocol Changes, Upgrades and Emergency Operations: Ideally made up 100% of technically skilled web3 developers or auditors who have experience with the Enzyme Protocol.

**Squad 2** : Strategy, Fees & Tokenomics: A team made up of technical experts who are very familiar with Enzyme and can help increase use-cases around MLN. Eg. Staking, gated communities, L1/L2 strategy, gameFi etc.

**Squad 3**: Grants, Ecosystem, Operations, Treasury & Accounting: Taking care of payments, accounting and making sure that treasury is managed efficiently. Made up 50:50 of investors with grant/ecosystem growth experience and user representatives who can work towards growing the protocol grants and strategically incentivizing the work that needs to be done.

The other change that we proposed involve reducing the quorum on squad 1 from 50% to a fixed 4 votes (irrespective of council size). As we grow, this will help the council to be able to react quickly to protocol changes or emergencies when required. 

This isn’t a plan we need to implement overnight, but something that we plan to work towards in phases. 

As a starting point, we will separate the Technical Council role and keeping the voting threshold at 50% for a council < 10 people and 40% for a council > 10 ppl. This involves growing the technical council.

**Growing the Technical Council** 
We’d like to invite anyone who feels they have the skill sets laid out below to apply to join the Enzyme Council.

**Minimum requirements:**

- Technically skilled in web3 and ideally experience writing or auditing contract code
- Keen interest in Enzyme as a DeFi Operating System
- Able to read and understand all of Enzyme’s audit reports
- Able to understand the architecture of Enzyme 
- Able to operate and check transactions with the help of an SOP
- Able to verify parameters of protocol related votes by decoding function data and/or simulating transactions.
- Checking payload of each transaction on Tenderly or similar tool.
- Speaking up when something doesn’t look right or not understood.
- Up to 2 hours to dedicate a week for transaction verification, signing and meetings.
- Experience with op-sec and handling ledgers securely

**Additional nice to haves:**

- Audit experience 
- Experiences as a recent active user or contributor of Enzyme
- Availability

**How do I apply?**
Please respond below with the following information:

**ETH Address:
ENS name:** 
(Optional but preferred)

**Why I want to be on the Enzyme Technical Council:**
(Your statement of intent)

**My Web3 technical qualifications:**
(Projects you’ve contributed to, DAOs you are a member of, previous delegate experience, etc.)

**My recent experience and involvement with Enzyme:**
(Code or audit contributions, social media engagement, usage of contracts, etc)

**Additional links:**
GitHub:
Additional relevant experience with Enzyme:
Other relevant information:

**What do I need to know?**
Known identities
Need to disclose any conflicts up front
Fiduciary duty
Remunerated role

**Application process will remain open until February 8th, 2022.**

**Comment by exa256** [comment]
I’m Exa, Technical Cofounder on the Exponent Team and I’d like to apply to be the member of Enzyme Technical Council.

### **Why I want to be on the Enzyme Technical Council:**

I have a shared vision for a DeFi operating system as an integral part of a technology stack. As someone who have developed decentralized applications since 2017, I do not believe a new crypto project should be developing a vault from scratch. I also believe that the Enzyme’s V4 has the most ideal architecture to realize this vision, and Exponent intends to develop products, services and compose DeFi strategies on an application layer in order to reduce development overhead, fasten our speed to market, while ensuring optimal smart contract security for our users.

My involvement as an Enzyme Technical Council member will ensure long term ecosystem value alignment. From that perspective, not only will I provide value in the form of integrator’s product and engineering feedback, but also add value as a representative ecosystem partner in the protocol. Increasing the ecosystem diversity in the form of additional tooling, clients and future smart contract plugins.

## **My Web3 technical qualifications:**

### Background:

- 4 years + of experience in Crypto (Crypto Class of 2017), started with Dapp development and Blockchain Network Infrastructure
- Software Product and Engineering, both as individual contributor and as a manager

### Relevant Technical Skills:

- lead an agile software team to design, develop and ship DeFi applications from end to end.
- knowledge in web3: smart contract development, dApp tooling via Hardhat and EthersJS
- ability to help debug mainnet transactions through the use of tenderly or ethtx, can understand and decode ABI-encoded inputs.
- Gnosis Multisig interactions on a daily basis, knowledge of standard key management opsec as part of a DAO organization.
- know how to set up alerts and notification systems for Gnosis multisig and Vault contract interaction through Tenderly and Discord notification bots.
- led interaction with an external team of auditors through extensive code audits

### My recent experience and involvement with Enzyme:

- I have worked together alongside Enzyme’s engineering team since Enzyme V3 to build and ship the Exponent Beta application to Ethereum mainnet.
- walked through and familiarized myself with Enzyme documentation and codebase at multiple level of integration:
    - smart contract: being one of the first to interact with Enzyme’s contracts from Solidity
    - backend service: custom rebalancer and trade service that submits batched transactions on Enzyme vault via Enzyme TypeScript SDK
    - frontend interaction: oversee and help lead technical direction for one of the first custom client-side applications that consumes Enzyme’s event logs and data API.
- Provide Enzyme’s team with technical feedback from the integration perspective
- Recently a speaker at E2 Summit

You can find me on:

Ethereum: exa256.eth
Email: exa@exponent.ai
GitHub: [https://github.com/exa256](https://github.com/exa256)

or on Exponent Discord:
[https://discord.gg/43jv3UKUeK](https://discord.gg/43jv3UKUeK)

**Comment by teawaterwire** [comment]
**ENS name:**
rigolo.eth

**Why I want to be on the Enzyme Technical Council:**
I'd like to apply to join the Enzyme Technical Council as I truly believe in Enzyme's mission of being the DeFi operating system. The protocol is already leading in that category but I think there are still a lot of exciting technical challenges ahead. I want to be able to contribute and help on future technical decisions.

**My Web3 technical qualifications:**
I started tinkering with web3 in 2017, then starting [Multis.co](https://multis.co/) as CTO in 2018 until April 2021. We were building crypto wallets for companies, starting from the Gnosis Multisig, then a GSN-enabled version of it, to finally build on top of the standard Gnosis Safe. We also connected to DeFi protocols (eg. first seamless multisig contract integrations to Kyber, Compound and TokenSets).

I'm a fullstack web3 engineer, from smart contracts code to interfaces with a strong experience around debugging transactions (eg. multisig'ed meta-transaction interacting with a DeFi protocol)

Since I left the startup world last year I've been focusing on diving deeper into Solidity and layer 2 languages, setting up a crypto.coliving DAO (coming soon) as well as playing around DeFi protocols, reading whitepapers and postmortems. 

For the record, I briefly worked last year with mStable to build a bribe contract for Curve voting wars, but one week before releasing it André released his own version of it, so we had to kill the project!


**My recent experience and involvement with Enzyme:**
At the beginning of last year I started my own [fund](https://app.enzyme.finance/vault/0xcc721874a2ee84198ef3a6a4c7ef7c642347d78a/overview) on Enzyme, getting 30+ depositors from friends and family. Gas fees have been tough but it's still amazing to be able to manage people's assets in a non-custodian way with all the fee calculations baked in the protocol!

Which led me to [propose an integration](https://github.com/enzymefinance/MFP/issues/9) to the PoolTogether protocol from Enzyme. I'm grateful it was accepted and I wrote the contract for this adapter. It made me go over many contracts that comprise the Enzyme protocol. I learned a lot and I believe it gives me a special knowledge of the architecture. 

Finally, ahead of the Sulu release I did my duty of testing the new protocol and app on Polygon as you can see [here](https://beta.sulu.enzyme.finance/vault/0xe7bbd529ae989a10687b9fac9244c753245b11aa) (as well as submitting feedbacks)

**Additional links:**
https://github.com/teawaterwire
https://twitter.com/teawaterwire
https://mirror.xyz/penseur.eth
https://teawaterwire.medium.com/

**Comment by ChainSecurityAudits** [comment]
**ENS name:**
chainsecurity.eth

**Why we want to be on the Enzyme Technical Council:**
ChainSecurity mission is to secure blockchain projects. We have been supporting Enzyme for many years in this regard and believe that joining the tech council to advocate for security and support in hands-on security allows us to further this mission, without compromising our strong believe in independence. While we we always abstain from any votes outside of those helping the security of the project, we believe that Enzyme values security as much as we do and that we can work together to both strengthen Enzyme and the overall Defi ecosystem towards mainstream adoption.

**Our Web3 technical qualifications:**
ChainSecurity was founded in 2017 as an ETH Zurich SpinOff after having developed Securify, an EVM static analyzer. ChainSecurity quickly grew and audited over 70 blockchain projects for more than 50 clients around the world for many of the major players in the Ethereum ecosystem
ChainSecurity received visibility during the Constantinople and Berlin hard forks by reporting critical vulnerabilities in Ethereum or it's main client.
At the beginning of 2020, ChainSecurity joined PwC Switzerland in order to provide a joint, stronger business offering covering smart contract assurance, regulatory reviews, custody reports and financial audit statements over crypto.
In April 2021, the ChainSecurity team separated from PwC, as it was challenging to serve clients from a regulated company. Made stronger by our business experience within PwC and after having inherited the best practices from the financial audit sector, the team of leading blockchain security engineers today brings quality, reliability, and experience to  major web3 projects.

**Our recent experience and involvement with Enzyme:**
We have been auditing all protocol upgrades for the last year and supported the previous council in on-chain verification of these. The audit reports are public and can be found on https://chainsecurity.com.

**Further comments**
As an independent auditor for many of the leading web3 projects, we are often in a position where we have confidential know-how. While it is rare that this will affect the tech council, we are committed to the following guidelines to ensure that we can fulfill our mission and stay independent:

* We will transparently disclose any remuneration received and any significant stake which we hold in the protocol
* We will abstain from all votes not related to the security of Enzyme
* We reserve the right to abstain without comment or justification from all votes in which our independence is or might be compromised. This especially concerns all votes related to choosing an auditor and any decision on integrating with or preventing integration with any other protocol.
* We will advocate for transparency and explain our actions as part of the tech council publicly at the earliest time possible while ensuring that this won't lower the security of the protocol.

We would be honored and proud to be voted into this role under these conditions and are looking forward to keep working together with Enzyme both as auditors and potentially in this new role as members of the tech council!

Additional links:
https://chainsecurity.com
https://twitter.com/chain_security
https://medium.com/@chain_security
